const { EmbedBuilder } = require("discord.js");

const quotes = {
motivational: [
"You don’t need to have everything figured out, you just need to take the next step forward.",
"Progress doesn’t always feel big, but even small steps still move you forward.",
"Some days will be harder than others, but that doesn’t mean you’re not improving.",
"You’ve already made it through things you once thought you couldn’t handle.",
"Growth takes time, and that’s okay.",
"You don’t need to rush, just don’t stop.",
"Every effort you make counts, even if it doesn’t show immediately.",
"You’re allowed to struggle and still keep going.",
"You’re stronger than the version of you that almost gave up.",
"It’s okay to rest, just don’t quit.",

"You don’t have to be perfect, just consistent.",
"Keep going, even if it feels slow.",
"You’re building something, even when it feels like nothing is happening.",
"The fact that you’re trying already matters.",
"You’ve come further than you think.",
"Don’t compare your progress to others.",
"Focus on your path, not someone else’s.",
"You don’t need motivation every day, just discipline.",
"Keep showing up for yourself.",
"You’re doing better than you realize.",

"It’s okay to start small.",
"You don’t need to wait for the perfect moment.",
"The best time to start was yesterday, the next best time is now.",
"You can handle more than you think.",
"You’ve already proven you can keep going.",
"Hard days don’t last forever.",
"You’re allowed to take your time.",
"You don’t need approval to move forward.",
"You are capable of more than you think.",
"You’re stronger than your doubts.",

"Don’t let one bad day stop your progress.",
"You’re still moving forward, even if it feels slow.",
"Keep working, results will come.",
"You don’t need to see the whole path, just the next step.",
"You’re building something meaningful.",
"Stay focused on what matters.",
"You’re not behind, you’re on your own timeline.",
"Keep going, even when it’s hard.",
"You’re closer than you think.",
"Trust the process.",

"You don’t need to be perfect to succeed.",
"You just need to keep going.",
"You’ve got this, even if it doesn’t feel like it.",
"Every step counts.",
"You’re improving every day.",
"Stay consistent.",
"Stay patient.",
"Stay focused.",
"Keep going.",
"And don’t stop now."
  ],

  romantic: [
"I don’t know how to explain it, but being around you just makes everything feel lighter, like somehow the world isn’t as heavy anymore.",
"If I had to choose between a perfect life or having you in it, I’d choose you every time without even thinking twice.",
"I’ve met a lot of people, but there’s just something about you that feels different in the best way possible.",
"You’re not just someone I like, you’re the kind of person I’d choose over and over again no matter what.",
"I didn’t believe in luck until I realized somehow out of everyone, I got to meet you.",
"It’s crazy how one person can just change your whole mood, and for me, that person is always you.",
"I don’t need a reason to smile anymore, because somehow you’ve already become that reason.",
"I could be having the worst day, but the moment I talk to you, everything just feels okay again.",
"You’re not just special, you’re the kind of person people wish they could find in a lifetime.",
"I don’t think you understand how rare it is to find someone like you in this world.",

"If I’m being honest, you’ve been on my mind way more than I probably should admit.",
"I didn’t plan on liking you this much, it just kind of happened without me realizing it.",
"There’s something about you that makes me want to be better without you even trying.",
"You don’t even have to try, you just naturally stand out from everyone else.",
"I don’t just like talking to you, I actually look forward to it every single time.",
"You’re the kind of person that makes everything feel more interesting just by being there.",
"I don’t think you realize how easy you make it for someone to fall for you.",
"You’re not just attractive, it’s your vibe that makes you unforgettable.",
"If I had one wish, it’d probably just be to spend more time with you.",
"You make things feel different, in a way I can’t really explain but don’t want to lose.",

"I don’t care about perfect, I just care about real, and you feel more real than anything else.",
"You’ve got this energy about you that just pulls people in without even trying.",
"It’s not just how you look, it’s everything about you that makes you stand out.",
"I could talk to you for hours and still not get bored, which honestly never happens.",
"You’re the kind of person that makes someone forget what they were even worried about.",
"I don’t know what it is, but being around you just feels right.",
"You’re not just someone I met, you’re someone I’m glad I didn’t miss.",
"I don’t think I’d ever get tired of hearing your voice or seeing your messages pop up.",
"You’ve got this way of making everything feel more calm just by being there.",
"You’re the type of person that makes people believe in something real again.",

"I didn’t expect you to mean this much to me, but now I can’t imagine not having you around.",
"You’re not just another person in my life, you’re someone I actually care about deeply.",
"You make everything feel more exciting without even trying to.",
"I don’t think I’ve ever met someone who feels as easy to be around as you.",
"You’re not just someone I like, you’re someone I respect and admire too.",
"You’ve got this calm confidence that’s honestly really attractive.",
"You don’t even realize how much of an impact you have just by being yourself.",
"You make everything feel more meaningful just by being part of it.",
"I don’t need anything fancy, just having you around already feels enough.",
"You’re not just someone I talk to, you’re someone I genuinely enjoy being with.",

"I think the best part about you is that you don’t even try to be special, you just are.",
"You’re the kind of person people don’t forget easily.",
"I don’t think you understand how naturally you stand out from everyone else.",
"You make everything feel more comfortable, like I can just be myself around you.",
"You’re not just interesting, you’re someone people actually want to keep around.",
"I didn’t expect you to become this important to me, but here we are.",
"You’re not just someone I met, you’re someone I’m really glad I did.",
"You’ve got this energy that just makes people want to stay.",
"I don’t know how you do it, but you make everything feel easier.",
"And honestly, if I had to choose again, I’d still choose you every time." 
  ],

  funny: [
"I tried to be productive today, but somehow I ended up doing absolutely nothing and still feeling tired like I worked a full shift.",
"I don’t know how people wake up early and function, because the moment I wake up I’m already thinking about going back to sleep.",
"I told myself I’d fix my sleep schedule, but clearly my sleep schedule had other plans for me.",
"I’m not lazy, I just feel like doing nothing is the most efficient use of my energy right now.",
"I start doing one thing, then suddenly I’m doing something completely different and I don’t even remember how I got there.",
"I open my phone for one minute and suddenly it’s been two hours and I’ve accomplished nothing.",
"I don’t need motivation, I need someone to do everything for me while I watch.",
"I say I’ll sleep early, then somehow I’m still awake at 3AM thinking about random things.",
"I try to save money, but then I remember I like buying things.",
"I don’t procrastinate, I just delay things until the last possible moment with style.",

"I wake up tired, stay tired, and go to sleep tired… it’s a full cycle.",
"I don’t need a gym, life is already exhausting enough.",
"I plan my day perfectly, then ignore the plan completely.",
"I always say I’ll be productive tomorrow, and tomorrow keeps moving.",
"I don’t have bad luck, I just have very interesting outcomes.",
"I try to focus, but my brain opens 50 tabs at once.",
"I’m not ignoring you, I just forgot to reply and now it’s too late.",
"I don’t need a break, I need a whole restart.",
"I start cleaning my room and end up finding something I lost years ago.",
"I don’t waste time, I just use it very creatively.",

"I’m not late, I just arrive exactly when I mean to… which is always late.",
"I try to fix one problem and somehow create three more.",
"I tell myself ‘just one more minute’ and suddenly it’s an hour later.",
"I don’t get distracted, I just follow unexpected opportunities.",
"I’m not unorganized, I just have a unique system that doesn’t work.",
"I open the fridge hoping something new magically appears.",
"I don’t know what I’m doing, but I’m doing it confidently.",
"I plan to sleep early, but my brain decides it’s time to think about life.",
"I don’t have energy, I just have moments of temporary motivation.",
"I try to relax, but somehow I stress about relaxing.",

"I don’t fail, I just learn in a very inconvenient way.",
"I say I’ll eat healthy, then I see food I like.",
"I don’t have a routine, I just react to whatever happens.",
"I tell myself to focus, but my thoughts go on a journey.",
"I don’t forget things, my brain just deletes them randomly.",
"I try to be serious, but life keeps being funny.",
"I don’t need plans, I just improvise everything.",
"I start something important, then suddenly I need a snack.",
"I don’t overthink, I just think way too much.",
"I try to stay calm, but everything tests my patience.",

"I don’t know what I’m doing with my life, but at least I’m consistent.",
"I try to fix things, but sometimes I just make them worse.",
"I don’t give up, I just pause for a long time.",
"I don’t have problems, I just have unexpected challenges.",
"I try to be organized, but chaos finds me.",
"I don’t need help, but I probably should get some.",
"I don’t plan ahead, I just hope things work out.",
"I try to stay focused, but everything distracts me.",
"I don’t lose motivation, it just disappears randomly.",
"I don’t know what’s going on, but I’m going with it."
  ],

 sad: [
"Sometimes you don’t realize how much something meant to you until it’s already gone.",
"It’s strange how someone can go from being your whole world to just a memory.",
"I keep telling myself I’m okay, but deep down I know I’m just getting used to the pain.",
"Some days aren’t bad, but they’re not good either… just empty.",
"It hurts more when you remember how things used to be.",
"I wish things could go back to how they were, even just for a moment.",
"It’s hard to move on when you’re still holding on to what you lost.",
"Sometimes the silence says more than words ever could.",
"I miss the version of us that used to exist.",
"You don’t always cry when you’re hurting, sometimes you just feel nothing.",

"It’s exhausting pretending everything is fine when it isn’t.",
"I don’t hate you, I just wish things didn’t end this way.",
"Some memories feel warm, but also hurt at the same time.",
"It’s hard to forget someone who gave you so much to remember.",
"I wish I could unfeel certain things.",
"Not everything broken can be fixed.",
"It’s not that I don’t care, I just don’t know what to do anymore.",
"I keep thinking about what could have been.",
"Sometimes you just have to accept things won’t go back to how they were.",
"It hurts more when you care more than the other person.",

"I didn’t expect things to change this much.",
"I wish I mattered as much as you did to me.",
"It’s hard when you feel like you’re slowly losing someone.",
"I try not to think about it, but it always comes back.",
"I miss what we had, even if it wasn’t perfect.",
"Sometimes people leave without saying goodbye.",
"It’s hard to let go when you still care.",
"I wish I could go back and change things.",
"It’s painful when effort isn’t returned.",
"I thought things would be different.",

"I’m tired of feeling like this.",
"It’s hard to explain what I’m feeling.",
"I wish things made more sense.",
"I feel lost sometimes.",
"I don’t know how to fix this.",
"I wish I could stop thinking about it.",
"It’s hard to move forward.",
"I feel stuck.",
"I don’t know what to do anymore.",
"I just feel tired.",

"Some days feel heavier than others.",
"I wish things were easier.",
"It’s hard to keep going sometimes.",
"I feel like I’m losing myself.",
"I don’t know how to feel anymore.",
"I just want peace.",
"I wish things didn’t hurt this much.",
"I feel alone even when I’m not.",
"I’m trying, but it’s hard.",
"I hope things get better."
],

wisdom: [
"Not everything needs a reaction, sometimes the smartest thing you can do is stay silent and observe.",
"You don’t have to prove anything to anyone, the right people will understand you without explanation.",
"Growth often feels uncomfortable, but that’s usually how you know you’re moving forward.",
"The way you respond to things says more about you than the situation itself.",
"Not every problem needs to be solved immediately, some things just need time.",
"Learning when to let go is just as important as knowing when to hold on.",
"Peace becomes more valuable the older you get.",
"Sometimes doing less actually leads to better results.",
"Understanding comes from listening, not just speaking.",
"You don’t always need answers right away, clarity comes with time.",

"Not everything deserves your energy, choose carefully where you invest it.",
"The more you understand people, the less you judge them.",
"Time has a way of revealing things you couldn’t see before.",
"Being calm in difficult situations is a form of strength.",
"Not every opportunity is meant for you, and that’s okay.",
"The way you think shapes the way you live.",
"Sometimes walking away is the wisest decision you can make.",
"You don’t need to control everything, some things are better left alone.",
"Experience teaches lessons that words never could.",
"The more you grow, the more your perspective changes.",

"Not everything that feels good is good for you, and not everything hard is bad for you.",
"Patience isn’t about waiting, it’s about how you act while waiting.",
"The quieter you become, the more you notice.",
"Wisdom is knowing when not to speak.",
"Every mistake carries a lesson if you’re willing to learn from it.",
"You don’t always need to win, sometimes you just need to understand.",
"Clarity often comes after confusion.",
"Sometimes the best decision is the one that protects your peace.",
"The way you handle failure matters more than failure itself.",
"Being aware of your thoughts is the first step to controlling them.",

"Not everything deserves your attention.",
"Sometimes less is more.",
"Understanding takes time.",
"You don’t need to rush everything.",
"Think before reacting.",
"Stay aware of your actions.",
"Your mindset shapes your reality.",
"Not every situation needs your input.",
"Sometimes silence is the best response.",
"Choose peace over chaos.",

"You learn more by observing than reacting.",
"Not everything is meant to be understood immediately.",
"Some lessons only make sense later.",
"Growth requires patience.",
"Stay grounded in who you are.",
"Not everything needs to be explained.",
"Your actions reflect your mindset.",
"Stay mindful of your choices.",
"Understanding others starts with understanding yourself.",
"Be aware of what truly matters.",

"Sometimes stepping back gives you a clearer view.",
"You don’t need to control every outcome.",
"Balance is more important than extremes.",
"Stay calm, even when things aren’t.",
"Your perspective changes everything.",
"Be intentional with your decisions.",
"Focus on what you can control.",
"Let go of what you can’t.",
"Stay present in the moment.",
"And learn from everything, even the small things."
]
};

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

module.exports = {
  name: "quote",

  async execute(interaction) {

    const category = interaction.options.getString("category");

    const selected = quotes[category];
    const quote = getRandom(selected);

    const embed = new EmbedBuilder()
      .setTitle("<:ItemSprites23:1449424903416840394> Quote")
      .setDescription(`${quote}`)
      .setColor("Purple");

    await interaction.reply({ embeds: [embed] });
  }
};